### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by Neargye**
Sorry, the last commit broke the build.
Did not notice the differences in the test/cmake string-view-lite and byte-lite.

Let's wait for the build of the requester, and then the sludge.
Now I kind of took the difference.

### CODE REVIEW

**Comment by Neargye** [comment]
in byte-lite `-std=c++${std}` and in string-view-lite `-std=${std}`, did not notice the difference first

**Comment by martinmoene** [comment]
There's a reason for project [non-std-lite](https://github.com/martinmoene/nonstd-lite) to exist ;)

Request: Would you mind to start issue/pr titles with an uppercase?

**Comment by Neargye** [comment]
Updated titles.

I try to withstand the style non-std-lite, once again sorry for the mistake.

**Comment by martinmoene** [comment]
The use of `17` over `c++17` to create option `std=c++17` stems from the desire to be easily able to use
```
# set( CMAKE_CXX_STANDARD ${std} )
```
sometime in the future (maybe).

Just updated  [nonstd-lite:test/CMakeLists.txt](https://github.com/martinmoene/nonstd-lite/blob/master/file/test/CMakeLists.txt) to that end.

**Comment by martinmoene** [comment]
Thanks!

**Pull request merged**
